services:
  database:
    image: amazon/dynamodb-local:latest
    container_name: database
    ports:
      - "8000:8000"
    command: " -jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  populate-data:
    image: amazon/aws-cli
    depends_on:
      - database
    environment:
      AWS_ENDPOINT: --endpoint-url=http://database:8000
    entrypoint: /bin/sh -c
    volumes:
      - "./database/init-scripts:/init-scripts"
      - "./database/data:/data"
    command: >
      '
       for script_name in /init-scripts/*.sh; do
         sh $$script_name
       done
      '